-- BOOLEAN

SELECT TRUE, FALSE, TRUE, FALSE, FALSE, TRUE;

CREATE TABLE STUD_INFO(
	ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(34),
    BRANCH VARCHAR(34),
    PASS BOOLEAN,
    PRIMARY KEY(ID)
);

INSERT INTO STUD_INFO(ID, NAME, pass) VALUES(1,'Peter',true), (2,'John',false); 
INSERT INTO STUD_INFO(ID, NAME, pass) VALUES(3,'Miller',2);  

SELECT ID, NAME, PASS FROM STUD_INFO;

 SELECT  ID, NAME, IF(pass, 'true', 'false') completed FROM STUD_INFO;  
 
 SELECT ID, NAME, PASS 
 FROM STUD_INFO
 WHERE PASS = TRUE;
 
 SELECT ID, NAME, PASS 
 FROM STUD_INFO 
 WHERE PASS IS TRUE;
 
 SELECT ID, NAME, PASS 
 FROM STUD_INFO
 WHERE PASS = FALSE;
 
 SELECT ID, NAME, PASS 
 FROM STUD_INFO
 WHERE PASS IS NOT TRUE;