-- NOT CONDITION -> The MySQL NOT condition is opposite of MySQL IN condition. It is used to negate a condition in a SELECT, INSERT, UPDATE or DELETE statement.

SELECT FIRST_NAME
FROM EMPLOYEE
WHERE FIRST_NAME NOT IN('Martin','Josheph', 'Belamidir', 'Stebin');


SELECT FIRST_NAME
FROM EMPLOYEE
WHERE FIRST_NAME NOT LIKE 'A%';

SELECT *
FROM EMPLOYEE
WHERE EMP_ID NOT BETWEEN 3 AND 5;

SELECT *
FROM EMPLOYEE
WHERE FIRST_NAME IS NOT NULL;