
SELECT ADDRESS, COUNT(*)
FROM FACULTY
GROUP BY ADDRESS;

SELECT SUM(SALARY) AS 'TOTAL SALARY OF ALL EMPLOYEE'
FROM FACULTY;

SELECT ID, NAME, SUM(SALARY) AS 'TOTAL SALARY OF EACH EMPLOYEE'
FROM FACULTY 
WHERE ID < 4
GROUP BY ID; 

SELECT NAME,ID, EMAIL, MIN(SALARY) AS 'MINIMUM OF EMPLOYEE'
FROM FACULTY
GROUP BY NAME, ID, EMAIL;

SELECT MIN(SALARY), ID, NAME, ADDRESS
FROM FACULTY
GROUP BY ID, NAME, ADDRESS;

SELECT MAX(SALARY)
FROM FACULTY;

