
-- ORDER BY
/*
SYNTAX ->
SELECT COLUMN1, COLUMN2, COLUMN3,... 
FROM TABLE_NAME
WHERE [CONDITION]
ORDER BY COLUMN_NAME ASC | DESC;
*/
-- ORDER BY ASC

SELECT NAME, ADDRESS, SALARY
FROM FACULTY
WHERE SALARY < 25000
ORDER BY SALARY ASC;

-- ORDER BY DESC 
SELECT ID, NAME, EMAIL
FROM FACULTY
WHERE ID < 4
ORDER BY NAME DESC;

-- ORDER BY BOTH ASC AND DESC 
SELECT ID, NAME, EMAIL, ADDRESS
FROM FACULTY
WHERE ID < 4
ORDER BY NAME ASC, ADDRESS DESC;