-- MYSQL CONSTRAINTS
/*
CONSTRAINTS
1. NOT NULL
2. CHECK
3. DEFAULT
4. PRIMARY KEY
5. AUTO_INCREMENT
6. UNIQUE
7. INDEX
8. ENUM
9. FOREIGN KEY
*/
/*
SYNTAX ->
CREATE TABLE TABLE_NAME(
	COLUMN_NAME1 DATATYPE CONSTRAINT,
    COLUMN_NAME1 DATATYPE CONSTRAINT,
    COLUMN_NAME1 DATATYPE CONSTRAINT,
    ----------- --------- -----------,
    COLUMN_NAMEn DATATYPE CONSTRAINT
);
*/
CREATE TABLE DMART(
	PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(32) DEFAULT 'MOBILE',
    PRODUCT_PRICE INT CHECK ( PRICE >= 2000),
    PRODUCT_BRAND VARCHAR(34),
    LOCATION ENUM('BHOPAL', 'BIHAR', 'MUMBAI'),
    EMAIL VARCHAR(43) UNIQUE,
    PRIMARY KEY(PRODUCT_ID)
);
    
    
    
    
    