
CREATE TABLE STUD_INFO(
	ID INT NOT NULL,
    FIRST_NAME VARCHAR(34),
    LAST_NAME VARCHAR(43),
    AGE INT
);

DESC STUD_INFO;

CREATE INDEX INDEX_AGE_FIRST_NAME
ON STUD_INFO(AGE, FIRST_NAME);

DESC STUD_INFO;

SHOW INDEXES FROM STUD_INFO;