
-- DELETE COLUMN 
-- SYNTAX -> DELETE FROM TABLE_NAME WHERE COLUMN_NAME = VALUE1;
DELETE FROM EMPLOYEE WHERE ID = 151;

SELECT *FROM EMPLOYEE;

-- DELETE AND LIMIT CLAUSE
-- SYNTAX -> DELETE FROM TABLE_NAME ORDER BY COLUMN_NAME LIMIT (2, 3, 4, ...);
DELETE FROM EMPLOYEE ORDER BY SALARY LIMIT 2;

SELECT *FROM EMPLOYEE;