-- USED TO SHOW ALL INDEXES IN EXSTING TABLE
SHOW INDEXES FROM EMP_INFO;

-- DROP THE INDEX
-- SYNTAX -> DROP INDEX INDEX_NAME ON TABLE_NAME;
DROP INDEX INDEX_CITY ON EMP_INFO;


SHOW INDEXES FROM EMP_INFO;

DROP INDEX INDEX_ID ON EMP_INFO;

SHOW INDEXES FROM EMP_INFO;