
SELECT *FROM EMP_INFO;

-- REPALCE
/*
SYNTAX
REPLACE INTO TABLE_NAME(COLUMN1, COLUMN2, COLUMN3, .....)
VALUES(VALUE1, VALUE2, VALUE3,.......);
*/
REPLACE INTO EMP_INFO(ID, NAME, CITY)
VALUES(6, 'MARTIN', 'INDIA');

SELECT *FROM EMP_INFO;


REPLACE INTO Person  
SET ID = 1,  
    Name = 'Mike',  
    City = 'Birmingham';