
-- CREATE INDEX IN MYSQL

CREATE INDEX INDEX_CITY
TYPE HASH
ON EMP_INFO(CITY);

-- SHOW INDEX
-- SYNTAX -> SHOW INDEXES FROM TABLE_NAME;
SHOW INDEXES FROM EMP_INFO;

SELECT ID, NAME, CITY
FROM EMP_INFO
WHERE WORKING_HOURS >= 10;

-- EXPLAIN ABOUT TABLE
EXPLAIN SELECT ID, NAME, CITY
FROM EMP_INFO
WHERE WORKING_HOURS >= 10;