
SHOW INDEXES FROM EMPLOYEE;

SHOW INDEXES FROM EMPLOYEE IN DB1;

 SHOW INDEXES IN table_name FROM database_name;  
 
 SHOW INDEXES FROM database_name.table_name; 
 
 
 SHOW KEYS FROM EMP_INFO IN DB1;
 
 CREATE INDEX PHONE ON EMP_INFO(PHONE) INVISIBLE;
 
 SHOW INDEXES FROM EMP_INFO;
 
 
 CREATE INDEX NAME ON EMP_INFO (NAME) COMMENT 'EMPLOYEE NAME';
 
 SHOW INDEXES FROM EMP_INFO;
 
 
 -- WHERE CLAUSE
 
 SHOW INDEXES FROM EMP_INFO WHERE VISIBLE = 'NO' OR INDEX_COMMENT = 'EMPLOYEE NAME';