-- CROSS JOIN -> 

/*
SELECT column-lists  
FROM table1  
CROSS JOIN table2; 
*/

SELECT CUSTOMER.CUSTOMER_ID, CUSTOMER.OCCUPATION, ORDERS.PROD_NAME
FROM ORDERS
CROSS JOIN CUSTOMER;

-- USING WHERE CLAUSE

SELECT CUSTOMER.CUSTOMER_NAME, CUSTOMER.OCCUPATION, ORDERS.PROD_NAME
FROM CUSTOMER
CROSS JOIN ORDERS
WHERE QUALIFICATION = 'BTECH';