
-- AGGREGATE FUNCTION

-- COUNT() -> COUNT FUNCTION IS USED TO COUNT THE NUMBER OF SPECIFIC COLUMN RECORD.
-- SYNTAX -> SELECT COUNT(COLUMN_NAME) [AS COLUMN] FROM TABLE_NAME;

SELECT COUNT(CUSTOMER_NAME) AS TOTAL_CUSTOMER FROM CUSTOMER;

/*
SUM() - > sum() function returns the total summed (non-NULL) value of an expression. 
It returns NULL if the result set does not have any rows. It works with numeric data type only.

SYNTAX - SELECT SUM(COLUMN_NAME) [AS ALIAS_NANME] FROM TABLE_NAME
*/
SELECT SUM(INCOME) AS TOTAL_INCOME FROM CUSTOMER;

-- SUM() WITH WHERE CLAUSE

SELECT SUM(INCOME) 
AS TOTAL_INCOME 
FROM CUSTOMER
WHERE CUSTOMER_ID BETWEEN 2 AND 4;

-- AVG() 
SELECT AVG(INCOME) AS AVERAGE_INCOME FROM CUSTOMER;

-- AVG() WITH WHERE CLAUSE
SELECT AVG(INCOME) 
AS AVERAGE_INCOME 
FROM CUSTOMER
WHERE INCOME BETWEEN 10000 AND 60000;

-- MIN() FUNCTION
SELECT MIN(INCOME) AS MINIMUM_INCOME FROM CUSTOMER;

-- MIN() WITH WHERE CLAUSE
SELECT MIN(INCOME) AS MINIMUM_INCOME FROM CUSTOMER 
WHERE CUSTOMER_ID BETWEEN 1 AND 4;

-- MAX()
SELECT MAX(INCOME) AS MAXIMUM_INCOME FROM CUSTOMER;

-- MAX() WITH WHERE CLAUSE
SELECT MAX(INCOME)
AS MAXIMUM_INCOME
FROM CUSTOMER 
WHERE QUALIFICATION = 'BTECH';

-- FIRST() -> FIRST() IS USED TO GET THE FIRST RECORD OF SPECIFIC COLUMN. 
SELECT OCCUPATION FROM CUSTOMER LIMIT 1;

-- LAST() -> LAST() IS USED TO GET THE LAST RECORD OF SPECIFIC COLUMN.
SELECT OCCUPATION FROM CUSTOMER ORDER BY CUSTOMER_ID DESC LIMIT 1;
