
-- COUNT()
SELECT COUNT(DISTINCT FNAME) FROM EMP;

-- COUNT() WITH WHERE CLAUSE
SELECT COUNT(*) 
AS 'BTECH' 
FROM CUSTOMER 
WHERE QUALIFICATION = 'BTECH';


-- SELECT EMPID, FNAME, COUNT(*) FROM EMP GROUP BY EMPID;


