
-- SYNTAX -> CREATE TABLE

-- CREATE TABLE TABLE_NAME(
-- 	COLUMN_DEFINITION1,
--     COLUMN_DEFINITION2,
--     ......,
--     TABLE_CONSTRAINTS
-- );

CREATE TABLE STUDENT(
 	ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    FEES INT,
    BRANCH VARCHAR(30),
    LOCATION VARCHAR(30),
   AGE INT, 
   STATUS BOOLEAN NOT NULL,
   PRIMARY KEY(ID)
);