-- DROP TABLE
/*
SYNTAX ->

DROP MULTIPLE TABLE
DROP TABLE table_name1, TABLE_NAME2, TABLE_NAME3,.....;  
OR,  
DROP TABLE schema_name.table_name;  
*/
-- BEFORE DROP TABLE 
SHOW TABLES;

-- DROP TABLE CITIES
DROP TABLE BAZAAR.CITIES;

-- AFTER DROP TABLE CITIES
SHOW TABLES;