USE MYDATABASE;

-- CHANGE COLUMN NAME
/*
SYNTAX
ALTER TABLE TABLE_NAME
CHANGE COLUMN OLD_COLUMN_NAME NEW_COLUMN_NAME DATATYPE,-------;
*/

ALTER TABLE STUDENTS
CHANGE COLUMN LOCATION ADDRESS VARCHAR(40);

SELECT *FROM STUDENTS;