-- temparory table
CREATE TEMPORARY TABLE TEMP_TABLE SELECT * FROM CUSTOMER LIMIT 0;  
SELECT *FROM TEMP_TABLE;
-- insert data in temp_table
INSERT INTO TEMP_TABLE VALUES(123,"MANISH","man@gmail.com", 49359395, "bhopal");

-- TEMPORARY TABLE CREATE AS A NORMAL TABLE BUT IN TEMPORARY TABLE WE USE TEMPORARY KEYWORD LIKE
/*
CREATE TEMPORARY TABLE TEMPORARY_TABLE(
	COLUMN_NAME1 COLUMN_DEFINITION,
    COLUMN_NAME2 COLUMN_DEFINITION,
    COLUMN_NAME3 COLUMN_DEFINITION,
    COLUMN_NAME4 COLUMN_DEFINITION,
    .......,
    COLUMN_NAMEn COLUMN_DEFINITION
);
*/
CREATE TEMPORARY TABLE Students( 
	student_name VARCHAR(40) NOT NULL, 
	total_marks DECIMAL(12,2) NOT NULL DEFAULT 0.00, 
	total_subjects INT UNSIGNED NOT NULL DEFAULT 0
);  
INSERT INTO Students(
	student_name, total_marks, total_subjects
) 
VALUES ('Joseph', 150.75, 2), 
	   ('Peter', 180.75, 2),
       ('Martin',143.52, 3); 
       
SELECT *FROM Students;
SELECT STUDENT_NAME, TOTAL_MARKS FROM STUDENTS;