
-- BEFORE TRUNCATE 
SELECT * FROM bazaar.student;

-- TRUNCATE -> TRUNCATE COMMAND USED TO DELETE ALL ROWS WITHOUT EFFECT ON TABLE STRUCTURE.
-- SYNTAX -> TRUNCATE TABLE TABLE_NAME;

TRUNCATE TABLE BAZZAR.STUDNET;