CREATE TABLE WRITE_LOCK_TABLE(
	ID INT NOT NULL,
    NAME VARCHAR(43),
    LOCATION VARCHAR(45),
    AGE INT
);
INSERT INTO WRITE_LOCK_TABLE VALUES
(100, 'MANISH', 'BHOPAL', 23),
(103, 'SANJU', 'BIHAR', 22),
(129, 'RAHUL', 'KOLKATA', 24),
(110, 'RANI', 'NEPAL', 21);

SELECT *FROM WRITE_LOCK_TABLE;

LOCK TABLES WRITE_LOCK_TABLE WRITE;

INSERT INTO WRITE_LOCK_TABLE VALUES
(120, 'MARTIN', 'LONDON', 34);

SELECT *FROM WRITE_LOCK_TABLE;
