
-- GRANT PRIVILEGES

CREATE USER MANISH@LOCALHOST IDENTIFIED BY 'MANISH@123';

SHOW GRANTS FOR MANISH@LOCALHOST;

GRANT ALL ON COLLEGE.*TO MANI@LOCALHOST;

SHOW GRANTS FOR MANISH@LOCALHOST;

GRANT SELECT ON STUDENTS TO EMP_INFO;