
-- SHOW ALL USER
SELECT USER FROM MYSQL.USER;

-- DROP SINGLE USER FROM MYSQL.USER
-- SYNTAX -> DROP USER USER_NAME;
DROP USER MANISHDB;

-- DROP MULTIPLE USER

-- DROP USER USER_NAME1, USER_NAME2,....;